ALTER TABLE posts ADD COLUMN category_id INTEGER REFERENCES categories(id);
ALTER TABLE posts ADD COLUMN user_id INTEGER REFERENCES users(id);
ALTER TABLE posts ADD COLUMN summary TEXT;
ALTER TABLE posts ADD COLUMN cover_image TEXT;
ALTER TABLE posts ADD COLUMN is_published BOOLEAN DEFAULT 0;
ALTER TABLE posts ADD COLUMN is_top BOOLEAN DEFAULT 0;
ALTER TABLE posts ADD COLUMN allow_comments BOOLEAN DEFAULT 1;
ALTER TABLE posts ADD COLUMN view_count INTEGER DEFAULT 0;