ALTER TABLE posts ADD COLUMN scheduled_at TIMESTAMP;
ALTER TABLE posts ADD COLUMN is_scheduled BOOLEAN DEFAULT 0;
ALTER TABLE posts ADD COLUMN draft_saved_at TIMESTAMP;
ALTER TABLE posts ADD COLUMN auto_save_draft BOOLEAN DEFAULT 1;
