ALTER TABLE posts ADD COLUMN slug TEXT;
ALTER TABLE posts ADD COLUMN excerpt TEXT;
ALTER TABLE posts ADD COLUMN status TEXT DEFAULT 'draft';
ALTER TABLE posts ADD COLUMN deleted_at TIMESTAMP;
ALTER TABLE posts ADD COLUMN published_at TIMESTAMP;

ALTER TABLE categories ADD COLUMN slug TEXT UNIQUE;
ALTER TABLE categories ADD COLUMN description TEXT;

ALTER TABLE tags ADD COLUMN slug TEXT UNIQUE;

CREATE TABLE IF NOT EXISTS media (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    filename TEXT NOT NULL,
    filepath TEXT NOT NULL,
    mimetype TEXT NOT NULL,
    size INTEGER NOT NULL,
    uploaded_by INTEGER REFERENCES users(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
